test: ../log_buffer.cpp ../client.cpp \
	../log.pb.cc ../logger.cpp ../main_client.cpp ../main_server.cpp ../mq.cpp ../process.cpp \
	../protobuf_tool.cpp ../server.cpp ../socket_tool_client.cpp ../socket_tool_server.cpp \
	../local_store_test.cpp ../test_test.cpp
g++ -o test -I /usr/local/include -L /usr/local/lib ../log_buffer.cpp ../client.cpp \
	../log.pb.cc ../logger.cpp ../main_client.cpp ../main_server.cpp ../mq.cpp ../process.cpp \
	../protobuf_tool.cpp ../server.cpp ../socket_tool_client.cpp ../socket_tool_server.cpp \
	../local_store_test.cpp ../test_test.cpp -lgtest -lpthread